Integration/E2E Tests and Fixes (#106)
* initial chart for integration test

* initial setup for k8s integration test in circle

* wait for job

* make tests more robust, fix data races

* fix another test race

* integration test (really e2e at this point)

* circleci

* circleci

* default secrets mapping, fix test races

* circleci

* circleci

* circleci

* add builder wrapper image

* kill buildkit sidecar on exit

* configurable builder image

* separate pg conn pool for listeners

* update vendor

* integration test fixes

* fix tests

* add sleeps and longer delay for fake tests

* rm old integration test config, update default builder image

* db maxconns, furanjob function

* acyl: fix chart options

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,8 @@
-version: 2
+version: 2.1
+orbs:
+  kubernetes: circleci/kubernetes@0.11.2
+  helm: circleci/helm@1.2.0
+
 jobs:
   build:
     docker:
@@ -31,8 +35,118 @@ jobs:
           working_directory: ./pkg
           environment:
             FURAN_TEST_DB: postgresql://postgres:root@localhost:5432/postgres?sslmode=disable
-          command: go test -coverprofile=profile.cov ./...
+          command: go test -race -coverprofile=profile.cov ./...
       - run:
           name: Test coverage
           working_directory: ./pkg
           command: go tool cover -func profile.cov |grep total |awk '{ print $3 }'
+
+  integration_test:
+    machine:
+      image: ubuntu-2004:202010-01
+    environment:
+      K8S_VERSION: v1.19.6
+      MINIKUBE_VERSION: v1.16.0
+    steps:
+      - checkout
+
+      # Build docker images (do this first so if it fails we don't bother w/ anything else)
+      - run:
+          name: build docker image
+          command: docker build -t furan2:integration .
+          environment:
+            DOCKER_BUILDKIT: 1
+      - run:
+          name: build docker image
+          command: docker build -t furan2-builder:integration .
+          working_directory: builder
+          environment:
+            DOCKER_BUILDKIT: 1
+
+      # Set up local k8s
+      - kubernetes/install-kubectl
+      - run:
+          name: setup minikube
+          command: |
+            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
+      - run:
+          name: setup conntrack
+          command: sudo apt update && sudo apt-get install -y conntrack
+      - run:
+          name: start minikube
+          command: |
+            sudo -E minikube start --vm-driver=none --kubernetes-version=${K8S_VERSION}
+      - run:
+          name: fix permissions
+          command: |
+            sudo chown -R circleci /home/circleci/.minikube/ &&
+            sudo chown -R circleci /home/circleci/.kube/
+      - run:
+          name: wait for minikube
+          command: |
+            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
+            until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
+              sleep 1;
+            done
+      - run:
+          name: set default RBAC
+          command: |
+            # make default account cluster-admin
+            kubectl create clusterrolebinding default-cluster-admin --clusterrole cluster-admin --serviceaccount=default:default
+
+      - run:
+          name: setup secrets
+          working_directory: testing/k8s
+          command: ./setup_cci_secrets.sh
+
+      # Install postgres
+      - helm/install-helm-chart:
+          chart: stable/postgresql
+          helm-version: v3.4.2
+          release-name: postgres
+          values-to-override: 'image.tag=12,postgresqlPassword=root,postgresqlDatabase=furan,persistence.enabled=false,fullnameOverride=postgresql'
+          wait: true
+
+      # Install furan server
+      - helm/install-helm-chart:
+          chart: ./.helm/charts/furan2
+          helm-version: v3.4.2
+          release-name: furan2
+          values-to-override: 'run_migrations=true,app.tls.use_dev_cert=true,app.secrets_backend=env,image.repository=furan2,image.tag=integration,is_dqa=true,serviceAccountName=default,app.builder_image=furan2-builder:integration'
+          wait: true
+
+      # Install integration test helm chart
+      - helm/install-helm-chart:
+          chart: ./.helm/charts/furan2-integration
+          helm-version: v3.4.2
+          release-name: furan2-integration
+          wait: false
+
+      - run:
+          name: wait for job completion
+          command: |
+            jobname="furan2-integration"
+            until [[ $SECONDS -gt 600 ]] ||
+              [[ $(kubectl get jobs ${jobname} -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}') == "True" ]] ||
+              [[ $(kubectl get jobs ${jobname} -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}') == "True" ]]; do
+              echo "waiting for job completion..."
+              sleep 5
+            done
+            success=$(kubectl get jobs ${jobname} -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}')
+            if [[ "${success}" == "True" ]]; then
+              echo "job success"
+              exit 0
+            else
+              echo "job failed or timeout"
+              kubectl get pods
+              kubectl describe pods
+              kubectl describe job/${jobname}
+              kubectl logs job/${jobname}
+              exit 1
+            fi
+workflows:
+  version: 2
+  build_and_test:
+    jobs:
+      - build
+      - integration_test
